### ISSUE TITLE
ROADMAP for project rewrite

### ISSUE THREAD

**Issue by anhzf** [anhzf/kpbi-membership#1]
- [x] Account and Authentication
  - [x] Login.
  - [x] Register.
  - [x] Forgot password.
  - [x] Send email verification.
  - [x] Change password.
  - [x] Update profile
- [x] Authorization
- [x] Membership
  - [x] Request membership verification.
  - [x] Membership verification request history.
  - [x] Notify membership verification status expiration.
  - [x] Notify membership verification status review.
  - [x] Update profile
    - [x] Update college
    - [x] Update program
    - [ ] ~Update head programs~
    - [x] Accreditations
  - [x] Print view
    - [x] Invoice
    - [x] Certificate
  - [x] Generate PDF
  - [x] List all members.
  - [x] Search/Filter members.
  - [x] View member profile.
  - [x] View member MBKM courses.
  - [x] Input MBKM courses.
- [x] Admin
  - [x] Membership
    - [x] Approve membership verification.
- [x] Legacy database migrations
